### ISSUE TITLE
Integration with other plugins

### ISSUE THREAD

**Issue by arniebradfo** [mukhortov/HESH-WordPress-Plugin#28]
- [ ] [Site Origin Editor](https://wordpress.org/plugins/so-widgets-bundle/) code editor widget - #16
- [ ] [Revisionary](https://wordpress.org/plugins/revisionary/) - #14 
- [ ] [Advanced Custom Fields](https://www.advancedcustomfields.com/) - #18 
- [ ] [Carbon Fields](https://wordpress.org/plugins/carbon-fields/) - #25 
- [] [Code Snippets CPT](https://wordpress.org/plugins/code-snippets-cpt/)  support `QTags.insertContent( text )` - #27 

Please reply with more suggestions

**Comment by robbymilo** [comment]
Perhaps look at this for ACF integration? https://github.com/ptasker/acf-code-field

**Comment by misfist** [comment]
+1 Advanced Custom Fields

**Comment by sanic3** [comment]
+1 Advanced Custom Fields

**Comment by vynnus** [comment]
Please add support for this one:
[genesis simple hooks](https://wordpress.org/plugins/genesis-simple-hooks/)

**Comment by webspilka** [comment]
+1  Carbon Fields Rich Text and Textarea fields
https://carbonfields.net/docs/fields-textarea/?crb_version=2-1-0

**Comment by DoggyWoggyWooWoo** [comment]
+1 for wooCommerce

**Comment by AleksIralda** [comment]
+1 for Advanced Custom Fields
